### ISSUE TITLE
code help

### ISSUE THREAD

**Issue by MrLihj** [TheToadAlly/HoughRectangle#1]
hello，I have seen your comments under this link https://github.com/lorenmt/facade-urban-analysis. I would like to ask if you have the code implemented in this paper-Local Regularity-driven City-scale Facade Detection from Aerial Images

**Comment by TheToadAlly** [comment]
No I did not implement this paper. I plan to implement this paper instead : http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.59.4239&rep=rep1&type=pdf
